name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Add npm cache
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm ci

      - name: Build Test
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          NEXT_PUBLIC_BASE_URL: ${{ secrets.PRODUCTION_URL }}

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          debug: true
          command_timeout: "30m"
          retries: 3
          sleep: 5s
          timeout: 60s
          envs: GITHUB_SHA
          script: |
            echo "Starting deployment..."
            cd chatgenius
            echo "Pulling latest changes..."
            git pull
            export SKIP_TYPE_CHECK=1
            export NODE_ENV=production

            echo "Installing dependencies..."
            npm ci

            echo "Building application..."
            npm run build

            echo "Restarting PM2..."
            if pm2 restart chatgenius-nichnarmada; then
              echo "PM2 restart successful"
            else
              echo "PM2 restart failed, attempting fresh start..."
              pm2 delete all || true
              pm2 start npm --name "chatgenius-nichnarmada" -- start
              pm2 save
            fi
